title: "A Test Feedstock of Recipes"
description: "Analysis-ready Zarr datasets derived from a dataset"
pangeo_forge_version: "0.3.3"
pangeo_notebook_version: "2021.05.04"
recipes:
  - id: a-recipe
    object: "recipe:recipe"
provenance:
  providers:
    - name: "A provider"
      description: "Someone gave us data"
      roles:
        - producer
        - licensor
      url: https://www.github.com/pangeo-forge
  license: "CC-BY-4.0"
maintainers:
  - name: "Maintainer"
    orcid: "0000-0001-5999-4917"
    github: maintainer
bakery:
  id: "a.bakery.id"
  target: a-target
  resources:
    memory: 4096
    cpu: 1024
